export const labels = {
  common: {
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    view: "View",
    delete: "Delete",
    search: "Search",
    active: "Active",
    expired: "Expired",
    loading: "Loading",
  },
  auth: {
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    welcome: "Welcome Back",
  },
  employee: {
    employeeNumber: "Lambarka Shaqaalaha / Employee Number / رقم الموظف",
    fullName: "Magaca oo Buuxa / Full Name / الاسم الكامل",
    titleEnglish: "Jagada Ingiriisi / English Title / المسمى بالإنجليزية",
    titleLocal: "Jagada Af-Soomaali / Local Title / المسمى المحلي",
    email: "Iimeyl / Email / البريد الإلكتروني",
    department: "Waaxda / Department / القسم",
    mobile: "Lambarka Taleefanka / Mobile Number / رقم الهاتف",
    nationalId: "Aqoonsiga Qaranka / National ID / الهوية الوطنية",
    address: "Cinwaanka / Address / العنوان",
    district: "Degmada / District / المنطقة",
    issueDate: "Taariikhda Bixinta / Issue Date / تاريخ الإصدار",
    expiryDate: "Taariikhda Dhicista / Expiry Date / تاريخ الانتهاء",
    personalInformation:
      "Macluumaadka Qofka / Personal Information / المعلومات الشخصية",
    contactLocation: "Contact & Location / الاتصال والموقع",
    identityDocumentation:
      "Dukumentiga Aqoonsiga / Identity Documentation / وثائق الهوية",
    employmentInformation: "Employment Information / معلومات العمل",
    digitalVerification: "Digital Verification",
    idValidity: "ID Validity / صلاحية الهوية",
    employeeManagement: "Employees",
    addEmployee: "Add Employee",
    editEmployee: "Edit Employee",
    backToList: "Back to List",
  },
  dashboard: {
    overview: "Overview",
    totalEmployees: "Total Employees",
    activeQrIds: "Active QR IDs",
    pendingRenewals: "Pending Renewals",
    activeStatus: "Active Status",
    employeeGrowthTrend: "Employee Growth Trend",
    departmentBreakdown: "Department Breakdown",
    latestOnboarding: "Latest Onboarding",
  },
  users: {
    userManagement: "Users",
    createUser: "Create User",
    role: "Role",
  },
  settings: {
    settings: "Settings",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm Password",
    updatePassword: "Update Password",
  },
} as const;
